FROM alpine:3.22.2@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412

SHELL ["/bin/ash", "-euo", "pipefail", "-c"]

HEALTHCHECK CMD ["/usr/bin/curl", "-fsSL", "--socks5", "localhost:9050", "--socks5-hostname", "localhost:9050", "https://check.torproject.org/api/ip"]

RUN apk upgrade --no-cache \
    && apk add --no-cache \
    bash=5.2.37-r0 \
    curl=8.14.1-r2 \
    gettext=0.24.1-r0 \
    git=2.49.1-r0 \
    tor=0.4.8.19-r0 \
    && apk cache --no-cache clean \
    && rm -rf /var/cache/apk/*

RUN chmod ugo+rwx /etc/tor

COPY {{ tor_torrc_file | default('torrc.template') }} /etc/tor/torrc
COPY tor-wrapper.sh /etc/tor/
COPY {{ tor_key_file | basename }} /var/lib/tor/keys/

RUN chmod ugo+rx /etc/tor/tor-wrapper.sh \
    && chown -R 100:101 /var/lib/tor/keys \
    && chmod 600 /var/lib/tor/keys/{{ tor_key_file | basename }}

USER "tor"

WORKDIR "/var/lib/tor"

EXPOSE 9050

ENTRYPOINT ["/etc/tor/tor-wrapper.sh"]

CMD []